THIS GOES ON
/etc/sddm.conf.d/20-kubuntu.conf
  
[Autologin]
Relogin=true
Session=plasma
User=ztge

[General]
HaltCommand=
RebootCommand=

[Theme]
Current=kubuntu
CursorSize=30
CursorTheme=breeze_cursors
Font=Noto Sans,10,-1,0,400,0,0,0,0,0,0,0,0,0,0,1

[Users]
MaximumUid=60000
MinimumUid=1000
