#!/bin/bash

# COMEÇA DIRETO NO DESKTOP

# 1. Altera para abrir o Desktop AGORA
sed -i 's/Session=.*/Session=plasma/' /etc/sddm.conf.d/20-kubuntu.conf
sed -i 's/User=.*/User=ztge/' /etc/sddm.conf.d/20-kubuntu.conf
sed -i 's/Relogin=.*/Relogin=true/' /etc/sddm.conf.d/20-kubuntu.conf
sync

# 2. Reinicia o SDDM (isso vai matar este script, mas tudo bem, ele já fez o papel dele)
systemctl restart sddm
