#!/bin/bash
# 1. Configura o arquivo oficial do Kubuntu para ir pro modo jogo
sed -i 's/Session=.*/Session=steam-gamescope/' /etc/sddm.conf.d/20-kubuntu.conf
sed -i 's/User=.*/User=ztge/' /etc/sddm.conf.d/20-kubuntu.conf
# Ativa o Relogin para forçar o SDDM a ignorar o medo de crash
sed -i 's/Relogin=.*/Relogin=true/' /etc/sddm.conf.d/20-kubuntu.conf
sync

# 2. O NOVO PULO DO GATO: O processo fantasma prepara o terreno para a volta
(
    # Espera você entrar no jogo tranquilamente
    sleep 3
    
    # Devolve o arquivo para o Desktop
    sed -i 's/Session=.*/Session=plasma/' /etc/sddm.conf.d/20-kubuntu.conf
    sed -i 's/User=.*/User=ztge/' /etc/sddm.conf.d/20-kubuntu.conf
    sed -i 's/Relogin=.*/Relogin=true/' /etc/sddm.conf.d/20-kubuntu.conf
    sync
) &

# 3. Mata o SDDM para iniciar o jogo agora
systemctl restart sddm
