#!/bin/bash

# INICIA DIRETO NO GAMEMODE

# 1. Configura o arquivo oficial do Kubuntu para ir pro DESKTOP agora
sed -i 's/Session=.*/Session=plasma/' /etc/sddm.conf.d/20-kubuntu.conf
sed -i 's/User=.*/User=ztge/' /etc/sddm.conf.d/20-kubuntu.conf
sed -i 's/Relogin=.*/Relogin=true/' /etc/sddm.conf.d/20-kubuntu.conf
sync

# 2. O PULO DO GATO INVERTIDO: O processo fantasma prepara a volta pro jogo
(
    # Espera o SDDM te logar no Desktop Plasma tranquilamente
    sleep 3
    
    # Devolve o arquivo para o Modo Jogo (para o próximo boot/logout)
    sed -i 's/Session=.*/Session=steam-gamescope/' /etc/sddm.conf.d/20-kubuntu.conf
    sed -i 's/User=.*/User=ztge/' /etc/sddm.conf.d/20-kubuntu.conf
    sed -i 's/Relogin=.*/Relogin=true/' /etc/sddm.conf.d/20-kubuntu.conf
    sync
) &

# 3. Reinicia o SDDM para sair do jogo e entrar no Desktop
systemctl restart sddm
